controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_joint
      - left_finger_joint
      - right_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# gripper_controller:
#   ros__parameters:
#     type: joint_trajectory_controller/JointTrajectoryController
#     joints:
#       - left_finger_joint
#       - right_finger_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity